/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        LinkedList chain = new LinkedList();
        chain.append(new Link("Gold"));
        chain.append(new Link("Silver"));
        chain.append(new Link("Bronze"));
        chain.traverse();
    }
}
